### ISSUE TITLE
Questions about RV32I verification

### ISSUE THREAD

**Issue by mole99** [riscv-non-isa/riscv-arch-test#279]
Hi, I am currently trying to verify a minimal RISC-V core (RV32I).

I have tried to strip down my configurations as much as possible:

isa.yaml:

```
hart_ids: [0]
hart0:
  ISA: RV32I
  physical_addr_sz: 32
  User_Spec_Version: '2.3'
  supported_xlen: [32]
```

platform.yaml:

```
nmi:
  label: nmi_vector
reset:
  label: reset_vector
```

I run riscof with this command:

```
riscof run --config ./config.ini --suite ./riscv-arch-test/riscv-test-suite/rv32i_m --env ./riscv-arch-test/riscv-test-suite/env
```

Riscof then runs all the tests from `riscv-test-suite/rv32i_m/I/src` on both the DUT and the reference implementation, all of which pass. But then it also runs a single test called `riscv-test-suite/rv32i_m/privilege/src/misalign1-jalr-01.S` which fails.

My question is whether it is correct that the last test was selected, since it seems to test something from the privileged architecture?

Does my core need to implement Machine-Level ISA? I thought because Zicsr is optional Machine-Level ISA is optional too.

Is it also necessarry for a RISC-V compliant core to implement interrupts? Because in the `platform.yaml` I cannot remove `nmi` without errors.

Sorry for all the questions. I appreciate any help :)
