### ISSUE TITLE
Need help on coverage mode test

### ISSUE THREAD

**Issue by trdthg** [riscv-non-isa/riscv-arch-test#542]
I'm just running a very basic coverage test with the following command

```
riscof coverage --config=config.ini --suite=riscv-arch-test/riscv-test-suite/ --env=riscv-arch-test/riscv-test-suite/env \
    --cgf-file=./riscv-arch-test/coverage/dataset.cgf \
    --cgf-file=./riscv-arch-test/coverage/i/rv64i.cgf \
    --cgf-file=./riscv-arch-test/coverage/priv/rv64i_priv.cgf
```

_spike_isa.yaml_ just enable RV64I:

```yaml
hart_ids: [0]
hart0:
  ISA: RV64I
  physical_addr_sz: 56
  User_Spec_Version: '2.3'
  supported_xlen: [64]
```

but all the coverage are 0

![image](https://github.com/user-attachments/assets/b6de55eb-ccd9-4f45-af79-da6348f007d3)

Is this normal?
